
expname: ${data.name}_${model.name}
workdir: ${oc.env:MODEL_DIR}/${expname}
core:
  version: 0.0.1
  tags:
    - mytag

hydra:
  run:
    dir: ${workdir}

  sweep:
    dir: ${workdir}
    subdir: ${hydra.job.num}_${hydra.job.id}

  job:
    env_set:
      WANDB_START_METHOD: thread
      WANDB_DIR: ./

defaults:
  - data: chain
  - model: chain
  - logging: default
  - optim: default
  - train: default
