# reproducibility
deterministic: False
random_seed: 42

# training

pl_trainer:
  fast_dev_run: False # Enable this for debug purposes
  gpus: 1
  precision: 32
  max_steps: 2e6
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 20.0
  limit_train_batches: 1.0
  limit_val_batches: 2000.0
  limit_test_batches: 1.0
  accelerator: ddp

monitor_metric: 'val_loss' # use acc loss 
monitor_metric_mode: 'min'

# early_stopping:
#   patience: 100
#   verbose: False

model_checkpoints:
  save_top_k: 1
  save_last: True
  verbose: False
